Vagrant.configure("2") do |config|
    config.vm.box = "debian\jessie64"
    config.vm.box_url = 'https://atlas.hashicorp.com/debian/boxes/jessie64'
    config.vm.network :private_network, ip: "192.168.56.101"

    config.vm.provider :virtualbox do |v|
        v.gui = true
        v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        v.customize ["modifyvm", :id, "--memory", 2048]
        v.customize ["modifyvm", :id, "--name", "debian\jessie64"]
    end

    config.vm.synced_folder "../www", "/var/www/sites/house_LED", create: true, type: "nfs"
    config.vm.synced_folder "../db", "/var/db", create: true, type: "nfs"
    config.vm.synced_folder "./config", "/var/custom_config_files", create: true, type: "nfs"
end
